name: Build portfolio website

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Install NPM packages
    #   run: npm install

    # - name: Install Angular CLI
    #   run: npm install -g @angular/cli

    # - name: Build webpage
    #   run: npm run build

    - name: Test GH Token Perms
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        env
        git config --global user.email "mikeyp.fennelly@gmail.com"
        git config --global user.name "Mikey Fennelly"
        git fetch origin github-pages
        git checkout github-pages
        touch hello.txt
        git add --all
        echo "****"
        git commit -am "added hello.txt"
        git push origin github-pages