name: Build portfolio website

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: node:20.10.0-alpine

    env: 
      GHA_PAT: ${{ secrets.GHA_PAT }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Add Git
      run: |
        apk update
        apk add git
        git --version

    - name: Install NPM packages
      run: npm install

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Build webpage
      run: ng build

    - name: Clone github-pages branch
      run: |
        git clone -b github-pages https://$GHA_PAT@github.com/mikeyfennelly1/portfolio/ github-pages
   
    - name: Copy website to github-pages branch
      run: cp -ra ./dist/portfolio/browser/* github-pages

    - name: Push github-pages branch changes
      run: |
        git config --global user.email "mikeyp.fennelly@gmail.com"
        git config --global user.name "Mikey Fennelly"
        cd github-pages
        git add --all
        git commit -m "committing all"
        git push https://$GHA_PAT@github.com/mikeyfennelly1/portfolio/ github-pages