name: Build portfolio website

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Build webpage
      run: npm run build