name: Build portfolio website

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    env: 
      GHA_PAT: ${{ secrets.GHA_PAT }}

    steps:
    - uses: actions/checkout@v2

    # - name: Install NPM packages
    #   run: npm install

    # - name: Install Angular CLI
    #   run: npm install -g @angular/cli

    # - name: Build webpage
    #   run: npm run build

    - name: Test GH Token Perms
      run: |
        git clone -b github-pages https://$GHA_PAT@github.com/mikeyfennelly1/portfolio/ github-pages
        git config --global user.email "mikeyp.fennelly@gmail.com"
        git config --global user.name "Mikey Fennelly"
        cd github-pages
        npm install
        ng build
        git add --all
        git push https://$GHA_PAT@github.com/mikeyfennelly1/portfolio/ github-pages